Walmart-Admin-Dashboard/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Walmart_Admin_Dashboard.Helper;
using Walmart_Admin_Dashboard.Models;

namespace Walmart_Admin_Dashboard.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
     
        public ActionResult Index(int? cid)
        {
            if (cid == null)
            {
                cid = TempData["cid"]!= null ? Convert.ToInt16(TempData["Cid"]) : 1;
            }
            var str = cid == 1 ? "USPROD" : "USCERT";
            var gmstr = cid == 1 ? "GMPROD" : "GMCERT";

            //for NHM
            if (cid == 3)
            {}
                //var NHMGrandMasterStatus = CheckGrandMasterIsRunning(str);
            
            var fcGrandMasterStatus = CheckGrandMasterIsRunning(str);

            var gmGrandMasterStatus = CheckGrandMasterIsRunning(gmstr);
            
            var fcAnalysisDate = GetCompletedAnalysisDt(str);
            var gmAnalysisdate = GetCompletedAnalysisDt(gmstr);
            var nmAnalysisDate = GetCompleteStreamsCount_NHM(str);

            var processingCompleteStatus = new ProcessingCompleteStatusViewModel
            {
                FCCompletedAnalysisDt = fcAnalysisDate,
                GMCompletedAnalysisDt = gmAnalysisdate,
                CompleteStreamsCount_NHM = nmAnalysisDate
            };

            //for PROD check OSA data Extract status 
            if (cid == 1)
            {
                var osaExtractStatus = GetOsaExtractStatus(str);
                if (osaExtractStatus.AnalysisDate != fcAnalysisDate.AnalysisDate)
                {
                    osaExtractStatus.CurrentFileCount = 0;
                    osaExtractStatus.ExpectedFiles = 106;
                    osaExtractStatus.StatusCode = "N";
                }
                processingCompleteStatus.OsaExtractStatus = osaExtractStatus;
                
            }

            var model = new OscaDashboardViewModel
            {
                FCConStr = str,
                GMConStr = gmstr,
                ProcessingCompleteStatus = processingCompleteStatus,
                FCGrandMasterStatus = fcGrandMasterStatus,
                GMGrandMasterStatus = gmGrandMasterStatus,
                

            };
            ViewBag.Conn = str;
            TempData["cid"] = cid;
            return View("Index", model);
        }

        public IEnumerable<GrandMasterStatus> CheckGrandMasterIsRunning(string connStr)
        {
            var dataset = ReportingDataGetter.CheckGrandMasterIsRunning(connStr);
            var result = dataset.Tables[0].AsEnumerable().ToList();
            var list = new List<GrandMasterStatus>();

            if (result != null && result.Count > 0)
            {
                foreach (var item in result)
                {
                    var row = new GrandMasterStatus
                    {
                        JobName = item["JobName"] != System.DBNull.Value ? item["JobName"].ToString() : string.Empty,
                         OriginatingServer = item["OriginatingServer"] != System.DBNull.Value ? item["OriginatingServer"].ToString() : string.Empty,
                         RunStarted = item["RunStarted"] != System.DBNull.Value ? Convert.ToDateTime(item["RunStarted"]).ToString("dd/MM/yyyy HH:mm") : string.Empty,
                        IsEnabled = item["IsEnabled"] != System.DBNull.Value ? Convert.ToInt16(item["IsEnabled"]) == 1 ? "Enabled": "Disabled": "Unknown",
                        IsRunning = item["IsRunning"] != System.DBNull.Value ? Convert.ToInt16(item["IsRunning"]) == 1 ? "Running" : "Stopped" : "Unknown",

                    };
                    list.Add(row);
                }
            }
            return list;
        
        }

        public CompletedAnalysisDate GetCompletedAnalysisDt(string connStr)
        {
            var dataset = ReportingDataGetter.CurrentAnalysisDate(connStr);
            var result = dataset.Tables[0].AsEnumerable().ToList();

            if (result != null && result.Count == 1)
            {
                var row = new CompletedAnalysisDate
                {
                    AnalysisDate = result[0]["AnalysisDate"] != System.DBNull.Value ? Convert.ToDateTime(result[0]["AnalysisDate"]).ToString("dd/MM/yyyy") : string.Empty,
                    CompleteCount = result[0]["CompleteCount"] != System.DBNull.Value ? result[0]["CompleteCount"].ToString() : string.Empty,
                    StreamsCount = result[0]["StreamsCount"] != System.DBNull.Value ? result[0]["StreamsCount"].ToString() : string.Empty,
                    GMTransferCount = result[0].Table.Columns.Contains("GMTransferCount") && result[0]["GMTransferCount"] != System.DBNull.Value ? result[0]["GMTransferCount"].ToString() : string.Empty
                };
                return row;

            }
            return new CompletedAnalysisDate();
        }
        //GetCompleteStreamsCount_NHM(str)
        public CompletedAnalysisDate GetCompleteStreamsCount_NHM(string connStr)
        {
            var dataset = ReportingDataGetter.GetCompleteStreamsCount_NHM(connStr);
            var result = dataset.Tables[0].AsEnumerable().ToList();

            if (result != null && result.Count == 1)
            {
                var row = new CompletedAnalysisDate
                {
                    AnalysisDate = result[0]["AnalysisDate"] != System.DBNull.Value ? Convert.ToDateTime(result[0]["AnalysisDate"]).ToString("dd/MM/yyyy") : string.Empty,
                    CompleteCount = result[0]["CompleteCount"] != System.DBNull.Value ? result[0]["CompleteCount"].ToString() : string.Empty,
                    StreamsCount = result[0]["StreamsCount"] != System.DBNull.Value ? result[0]["StreamsCount"].ToString() : string.Empty
                };
                return row;

            }
            return new CompletedAnalysisDate();
        }


       public OsaDataExtractStatus GetOsaExtractStatus(string connStr)
        {
            var dataset = ReportingDataGetter.GetOsaExtractStatus(connStr);
            var result = dataset.Tables[0].AsEnumerable().ToList();

            if (result != null && result.Count ==1)
            {
                    var row = new OsaDataExtractStatus
                    {
                        AnalysisDate = result[0]["AnalysisDate"] != System.DBNull.Value ? Convert.ToDateTime(result[0]["AnalysisDate"]).ToString("dd/MM/yyyy") : string.Empty,
                        StatusCode = result[0]["StatusCode"] != System.DBNull.Value ? result[0]["StatusCode"].ToString() : string.Empty,
                        LastModifiedDateTime = result[0]["LastModifiedDateTime"] != System.DBNull.Value ? Convert.ToDateTime(result[0]["LastModifiedDateTime"]).ToString("dd/MM/yyyy HH:mm") : string.Empty,
                        ExpectedFiles = result[0]["ExpectedFiles"] != System.DBNull.Value ? Convert.ToInt32(result[0]["ExpectedFiles"]):0,
                        CurrentFileCount = result[0]["CurrentFileCount"] != System.DBNull.Value ? Convert.ToInt16(result[0]["CurrentFileCount"]) :0,
                    };
                   return row;
            }
            return new OsaDataExtractStatus();

        }


        


        //// POST: Dashboard/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Walmart-Admin-Dashboard/Controllers/StagingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Walmart_Admin_Dashboard.Helper;
using Walmart_Admin_Dashboard.Models;

namespace Walmart_Admin_Dashboard.Controllers
{
    public class StagingController : Controller
    {
        // GET: Staging
        public ActionResult Index(int? cid)
        {
            if (cid == null)
            {
                cid = TempData["cid"] != null ? Convert.ToInt16(TempData["Cid"]) : 1;
            }
            
            var str = cid == 1 ? "USPROD" : "USCERT";

            var dataset = GetStagingData(str, string.Empty, string.Empty, string.Empty, null,null, "FC");

            var taskHistory = dataset.Tables[3].AsEnumerable().ToList();
            var taskHistoryData = new List<TaskHistoryViewModel>();
            if (taskHistory != null)
            {
                taskHistoryData = GetTaskHistoryData(taskHistory).ToList();
            }

            var tasksInProgressData = new List<TasksInProgressViewModel>();
            var taskInProgress = dataset.Tables[2].AsEnumerable().ToList();
            if(taskInProgress!=null)
            {
                tasksInProgressData = GetTasksInProgressData(taskInProgress).ToList();
            }
            

            var model = new StagingDataModel()
            {
                TaskHistory = taskHistoryData,
                TasksInProgress = tasksInProgressData,
            };
            TempData["cid"] = cid;
            ViewBag.Conn = str;
            return View("Index", model);
    }

        public ActionResult ApplyFilter(string cid, string status, string taskDescr, string fileName, DateTime? taskStart, DateTime? taskEnd, string market)
        { 
            if (cid == null)
            {
                cid = TempData["cid"] != null ? TempData["Cid"].ToString() : "1";
            }

            var str = cid == "1" ? "USPROD" : "USCERT";
            var dataset = GetStagingData(str,status, taskDescr, fileName, taskStart, taskEnd, market);
            var taskHistory = dataset.Tables[3].AsEnumerable().ToList();
            var taskHistoryData = new List<TaskHistoryViewModel>();
            if (taskHistory != null)
            {
                taskHistoryData = GetTaskHistoryData(taskHistory).ToList();
            }
            var tasksInProgressData = new List<TasksInProgressViewModel>();
            var taskInProgress = dataset.Tables[2].AsEnumerable().ToList();
            if (taskInProgress != null)
            {
                tasksInProgressData = GetTasksInProgressData(taskInProgress).ToList();
            }


            var model = new StagingDataModel()
            {
                TaskHistory = taskHistoryData,
                TasksInProgress = tasksInProgressData,
            };
            TempData["cid"] = cid;
            ViewBag.Conn = str;
           // return View("Index", model);

            return PartialView("_StagingView", model);
        }
        private DataSet GetStagingData(string connStr, string status,string taskDescr,  string fileName, DateTime? taskStart, DateTime? taskEnd, string market)
        {
            return ReportingDataGetter.GetStagingQuery(connStr, status, taskDescr, fileName, taskStart, taskEnd, market);
        }
        public IEnumerable<TaskHistoryViewModel> GetTaskHistoryData(List<DataRow> result)
        {
            var list = new List<TaskHistoryViewModel>();
           
                foreach (var item in result)
                {

                    var row = new TaskHistoryViewModel
                    {
                        Market = item["Market"] != DBNull.Value ? item["Market"].ToString() : "FC",
                        TaskDescription = item["TaskDescription"] != System.DBNull.Value ? item["TaskDescription"].ToString() : string.Empty,
                        ProcMins = item["ProcMins"] != System.DBNull.Value ? Convert.ToInt32(item["ProcMins"]) : 0,
                        TaskID = item["TaskID"] != System.DBNull.Value ? item["TaskID"].ToString() : string.Empty,
                        FileName = item["FileName"] != System.DBNull.Value ? item["FileName"].ToString() : string.Empty,
                        ControlID = item["ControlID"] != System.DBNull.Value ? item["ControlID"].ToString() : string.Empty,
                        TaskStart = item["TaskStart"] != System.DBNull.Value ? Convert.ToDateTime(item["TaskStart"]).ToString("dd/MM/yyyy HH:mm") : string.Empty,
                        TaskEnd = item["TaskEnd"] != System.DBNull.Value ? Convert.ToDateTime(item["TaskEnd"]).ToString("dd/MM/yyyy HH:mm") : string.Empty,
                        StatusCode = item["StatusCode"] != System.DBNull.Value ? item["StatusCode"].ToString() : string.Empty,
                        AttemptNo = item["AttemptNo"] != System.DBNull.Value ? item["AttemptNo"].ToString() : string.Empty,
                    };
                    list.Add(row);
                }
            
            return list;
        }
        public IEnumerable<TasksInProgressViewModel> GetTasksInProgressData(List<DataRow> result)
        {
            var list = new List<TasksInProgressViewModel>();
           
                foreach (var item in result)
                {

                    var row = new TasksInProgressViewModel
                    {
                        TaskDescription = item["TaskDescription"] != System.DBNull.Value ? item["TaskDescription"].ToString() : string.Empty,
                        ProcMins = item["ProcMins"] != System.DBNull.Value ? Convert.ToInt32(item["ProcMins"]) : 0,
                        TaskID = item["TaskID"] != System.DBNull.Value ? item["TaskID"].ToString() : string.Empty,
                        TaskInstanceID = item["TaskInstanceID"] != System.DBNull.Value ? item["TaskInstanceID"].ToString() : string.Empty,
                        TaskStart = item["TaskStart"] != System.DBNull.Value ? Convert.ToDateTime(item["TaskStart"]).ToString("dd/MM/yyyy HH:mm") : string.Empty
                       
                    };
                    list.Add(row);
                }
            
            return list;
        }
        
    }
}

Walmart-Admin-Dashboard/Views/Staging/Index.cshtml
@model Walmart_Admin_Dashboard.Models.StagingDataModel
@{
    ViewBag.Title = "Osca Staging";
    var cid = TempData["cid"];
}

<h2>Walmart OSCA Data Loading</h2>
<div class="row">
    <div class="col-md-8">
        <span style="font-size: 1.5rem; font-weight:500">Database: @ViewBag.Conn  </span> 
    </div>
    <div class="col">
        <span style="float:right">@Html.ActionLink("View Processing", "Index", "Processing", new { cid = cid }, new { @class = "btn" })</span>
</div>
    <div class="col">
        <span style="float:right">
            @Html.ActionLink("View Dashboard", "Index", "Dashboard", new { cid = cid }, new { @class = "btn" })
        </span>
    </div>
    </div>


@*@Html.Partial("_TaskHistory", Model.TaskHistory)*@

<a class="link" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
   Open Filters To Find Tasks
</a>

<div class="collapse" id="collapseExample">
    <form class="panel panel-default" style="font-size:12px; background-color: #eeeeee;">
        @*<div class="panel-heading">Find Tasks</div>*@
        <div class="panel-body">
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="statusSelect" class="col-sm-3 col-form-label-sm" id="lbl">Status Code</label>
                    <div class="col-sm-9">
                        <select class="form-control form-control-sm" id="statusSelect">
                            <option value="">Select Task Status</option>
                            <option value="C">Complete</option>
                            <option value="P">Pending</option>
                            <option value="F">Failed</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="marketSelect" class="col-sm-3 col-form-label-sm" id="lbl">Select Market</label>
                    <div class="col-sm-9">
                        <select class="form-control form-control-sm" id="marketSelect">

                            <option value="FC" selected="selected">FC</option>
                            <option value="NHM">NHM</option>
                            <option value="GM">GM</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="taskDescrTxt" class="col-sm-3 col-form-label-sm">Task Description</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control form-control-sm" id="taskDescrTxt" title="Task Description">
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="fileNameTxt" class="col-sm-3 col-form-label-sm">File Name</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control form-control-sm" id="fileNameTxt" title="File Name">
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <label for="taskStartTxt" class="col-sm-3 col-form-label col-form-label-sm">Task Start From:</label>
                    <div class="col-sm-9">
                        <input type="datetime-local" class="form-control form-control-sm" id="taskStartTxt" title="Task Start Date">
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="taskEndTxt" class="col-sm-3  col-form-label-sm">Task Start To:</label>
                    <div class="col-sm-9">
                        <input type="datetime-local" class="form-control form-control-sm" id="taskEndTxt" title="Task End Date">
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <button type="button" class="btn btn-default" id="btnApplyFilter" title="ApplyFilter">Apply Filter</button>
                    <input type="reset" class="btn btn-default">
                </div>
            </div>
        </div>
    </form>
</div>


    @if (Model != null)
    {
        <div id="Partial">
            @Html.Partial("_StagingView", Model)


        </div>

    }

    <script type="text/javascript" language="javascript">
        // $('#btnApplyFilter').click(function () {
        $(document).on('click', '#btnApplyFilter', function () {
            $.blockUI();
            setTimeout($.unblockUI, 1500);
            //var urlParams = new URLSearchParams(window.location.search);
            //var cid = urlParams.get('cid');
            var cid = getQueryStringValue("cid")

            var status = $('#statusSelect').val();
            var taskDescr = $('#taskDescrTxt').val();
            var fileName = $('#fileNameTxt').val();
            var taskStart = $('#taskStartTxt').val();
            var taskEnd = $('#taskEndTxt').val();
            var market = $('#marketSelect').val();

            ApplyFilter(cid, status, taskDescr, fileName, taskStart, taskEnd, market);
            // $.unblockUI();
        });

        function ApplyFilter(cid, status, taskDescr, fileName, taskStart, taskEnd, market) {
            $("#Partial").load('@Url.Action("ApplyFilter", "Staging")', {
                cid: cid, status: status, taskDescr: taskDescr,
                fileName: fileName, taskStart: taskStart, taskEnd: taskEnd, market: market
            });
        }




    </script>

Walmart-Admin-Dashboard/Views/Staging/_StagingView.cshtml
@model Walmart_Admin_Dashboard.Models.StagingDataModel


@if (Model.TasksInProgress != null)
    {
    <h4>Tasks In Progress</h4>
    <div id="tpPartial">
        @Html.Partial("_TasksInProgress", Model.TasksInProgress)
    </div>
    }
 @if (Model.TaskHistory != null && Model.TaskHistory.Count() > 0)
    {
    <h4>Tasks History</h4>

    <div id="thPartial">
        @Html.Partial("_TaskHistory", Model.TaskHistory)
    </div>
    }
@*
    <div id="thPartial">
        @Html.Partial("_TasksInProgress", Model.TasksInProgress)
    </div>
       <table class="table table-striped table-bordered dashboard-table">
                <thead class="headerRow">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => Model.TasksInProgress.TaskDescription)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => Model.TasksInProgress.TaskInstanceID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => Model.TasksInProgress.TaskID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => Model.TasksInProgress.TaskStart)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => Model.TasksInProgress.ProcMins)
                        </th>

                    </tr>
                </thead>
                @foreach (var item in Model.TasksInProgress)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TaskDescription)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TaskInstanceID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TaskID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TaskStart)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProcMins)
                        </td>

                    </tr>
                }

            </table>
*@

Walmart-Admin-Dashboard/Views/Staging/_TaskHistory.cshtml
@model IEnumerable<Walmart_Admin_Dashboard.Models.TaskHistoryViewModel>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@

<table class="table table-striped table-bordered dashboard-table">
    <thead class="headerRow">
        <tr>
            <th>  Market</th>
            <th>  Task Description</th>
            <th>
                @Html.DisplayNameFor(model => model.ProcMins)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ControlID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskEnd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatusCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AttemptNo)
            </th>

        </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Market)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProcMins)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ControlID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskEnd)
                </td>
                @{ 
                    var bgColour = item.StatusCode=="F" ? "background-color:#ffc7ce" : "";
                }
                <td style=@bgColour>@item.StatusCode </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AttemptNo)
                </td>

            </tr>
        }

</table>

Walmart-Admin-Dashboard/Views/Staging/_TasksInProgress.cshtml
@model IEnumerable<Walmart_Admin_Dashboard.Models.TasksInProgressViewModel>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table table-striped table-bordered dashboard-table">
    <thead class="headerRow">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TaskDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskInstanceID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProcMins)
            </th>

        </tr>
    </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskInstanceID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProcMins)
                </td>
                @*<td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>*@
            </tr>
        }

</table>