Walmart-Admin-Dashboard/Controllers/ProcessingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Walmart_Admin_Dashboard.Helper;
using Walmart_Admin_Dashboard.Models;

namespace Walmart_Admin_Dashboard.Controllers
{
    public class ProcessingController : Controller
    {
        // GET: Processing
        public ActionResult Index(int? cid)
        {
            if (cid == null)
            {
                cid = TempData["cid"] != null ? Convert.ToInt16(TempData["Cid"]) : 1;
            }
            var str = cid == 1 ? "USPROD" : "USCERT";
            var gmstr = cid == 1 ? "GMPROD" : "GMCERT";

           

            var fc = GetStillToProcess(str, "FC");
            var gm = GetStillToProcess(gmstr, "GM");
            var nm = GetStillToProcess(str,"NHM");

            var fcAnalysisDate = GetCompletedAnalysisDt(str);
            var gmAnalysisdate = GetCompletedAnalysisDt(gmstr);
            var nmAnalysisDate = GetCompleteStreamsCount_NHM(str);

            var processingCompleteStatus = new ProcessingCompleteStatusViewModel
            {
                FCCompletedAnalysisDt = fcAnalysisDate,
                GMCompletedAnalysisDt = gmAnalysisdate,
                CompleteStreamsCount_NHM = nmAnalysisDate
            };
            var model = new Walmart_Admin_Dashboard.Models.OscaProcessViewModel()
                {
                    FCStillToProcess = fc,
                    GMStillToProcess = gm,
                    NHMStillToProcess = nm,
                    ProcessingCompleteStatus = processingCompleteStatus

                };
            //for PROD check OSA data Extract status and GM copy over
            if (cid==1)
            {
                var osaExtractStatus = GetOsaExtractStatus(str);
                if (osaExtractStatus.AnalysisDate != fcAnalysisDate.AnalysisDate)
                {
                    osaExtractStatus.CurrentFileCount = 0;
                    osaExtractStatus.ExpectedFiles = 106;
                }
                processingCompleteStatus.OsaExtractStatus = osaExtractStatus;

                var gmCopy = GetGMCopyover(0, str);
                model.GMCopyover = gmCopy;
            }
           
           
            

            ViewBag.Conn = str;
            TempData["cid"] = cid;
            return View("Index", model);
        }
        public IEnumerable<StillToProcessViewModel> GetStillToProcess(string connStr, string market)
        {
            var list = new List<StillToProcessViewModel>();
            
            var dataset = ReportingDataGetter.ReturnStillToProcessData(connStr, market);
            var result = dataset.Tables[0].AsEnumerable().ToList();

            if (result != null)
            {
                foreach (var item in result)
                {

                    var row = new StillToProcessViewModel
                    {
                        ControlID = item["ControlID"].ToString(),
                        TimeBucket = item["TimeBucket"].ToString(),
                        StreamID = item["StreamID"].ToString(),
                        AnalysisDate = Convert.ToDateTime(item["AnalysisDate"]).ToShortDateString(),
                        ControlRunStartDateTime = item["ControlRunStartDateTime"] != System.DBNull.Value ? item["ControlRunStartDateTime"].ToString() : string.Empty,//"dd/MM/yyyy HH:mm"
                        ControlStageStartDateTime = item["ControlStageStartDateTime"] != System.DBNull.Value ? item["ControlStageStartDateTime"].ToString() : string.Empty,
                        ControlStageEndDateTime = item["ControlStageEndDateTime"] != System.DBNull.Value ? item["ControlStageEndDateTime"].ToString() : string.Empty,
                        ControlExtractStartDateTime = item["ControlExtractStartDateTime"] != System.DBNull.Value ? item["ControlExtractStartDateTime"].ToString() : string.Empty,
                        ControlExtractEndDateTime = item["ControlExtractEndDateTime"] != System.DBNull.Value ? Convert.ToDateTime(item["ControlExtractEndDateTime"]).ToString() : string.Empty,
                        Duration = item["Duration"] != System.DBNull.Value ? Convert.ToInt32(item["Duration"]) : 0
                    };
                    list.Add(row);
                }
            }
            return list;
        }
        public IEnumerable<GMCopyoverViewModel> GetGMCopyover(int showHistory, string connStr)
        {
            var list = new List<GMCopyoverViewModel>();
            var dataset = ReportingDataGetter.GetGMReportingCopyover(showHistory, connStr);
            var result = dataset.Tables[0].AsEnumerable().ToList();

            if (result != null)
            {
                foreach (var item in result)
                {

                    var row = new GMCopyoverViewModel
                    {
                        AnalysisDate = item["AnalysisDate"] != System.DBNull.Value ? Convert.ToDateTime(item["AnalysisDate"]).ToShortDateString() : string.Empty,
                        TableName = item["TableName"] != System.DBNull.Value ? item["TableName"].ToString() : string.Empty,//"dd/MM/yyyy HH:mm"
                        AvgTransferDuration = item["AvgTransferDuration"] != System.DBNull.Value ? Convert.ToInt32(item["AvgTransferDuration"]) : 0,
                        NumComplete = item["NumComplete"] != System.DBNull.Value ? Convert.ToInt32(item["NumComplete"]) : 0,
                        MainlandComplete = item["MainlandComplete"] != System.DBNull.Value ? item["MainlandComplete"].ToString() : string.Empty,
                        Complete159 = item["Complete159"] != System.DBNull.Value ? item["Complete159"].ToString() : string.Empty,
                        Complete160 = item["Complete160"] != System.DBNull.Value ? item["Complete160"].ToString() : string.Empty

                    };
                    list.Add(row);
                }
            }
            return list;
        }
        public ActionResult LoadGMCopyover(string cid, bool chk)
        {
            var conStr = !string.IsNullOrEmpty(cid) ? cid == "1" ? "USPROD" : "USCERT" : "USPROD";
            var isChecked = chk ? 1 : 0;
            var gmCopy = GetGMCopyover(isChecked, conStr);
            var model = new List<GMCopyoverViewModel>();
            model = gmCopy.ToList();
            return PartialView("_GMCopyOver", model);
        }
        public CompletedAnalysisDate GetCompletedAnalysisDt(string connStr)
        {
            var dataset = ReportingDataGetter.CurrentAnalysisDate(connStr);
            var result = dataset.Tables[0].AsEnumerable().ToList();

            if (result != null && result.Count == 1)
            {
                var row = new CompletedAnalysisDate
                {
                    AnalysisDate = result[0]["AnalysisDate"] != System.DBNull.Value ? Convert.ToDateTime(result[0]["AnalysisDate"]).ToString("dd/MM/yyyy") : string.Empty,
                    CompleteCount = result[0]["CompleteCount"] != System.DBNull.Value ? result[0]["CompleteCount"].ToString() : string.Empty,
                    StreamsCount = result[0]["StreamsCount"] != System.DBNull.Value ? result[0]["StreamsCount"].ToString() : string.Empty,
                    GMTransferCount = result[0].Table.Columns.Contains("GMTransferCount") && result[0]["GMTransferCount"] != System.DBNull.Value ? result[0]["GMTransferCount"].ToString() : string.Empty

                };
                return row;

            }
            return new CompletedAnalysisDate();
        }
        public OsaDataExtractStatus GetOsaExtractStatus(string connStr)
        {
            var dataset = ReportingDataGetter.GetOsaExtractStatus(connStr);
            var result = dataset.Tables[0].AsEnumerable().ToList();

            if (result != null && result.Count == 1)
            {
                var row = new OsaDataExtractStatus
                {
                    AnalysisDate = result[0]["AnalysisDate"] != System.DBNull.Value ? Convert.ToDateTime(result[0]["AnalysisDate"]).ToString("dd/MM/yyyy") : string.Empty,
                    StatusCode = result[0]["StatusCode"] != System.DBNull.Value ? result[0]["StatusCode"].ToString() : string.Empty,
                    LastModifiedDateTime = result[0]["LastModifiedDateTime"] != System.DBNull.Value ? Convert.ToDateTime(result[0]["LastModifiedDateTime"]).ToString("dd/MM/yyyy HH:mm") : string.Empty,
                    ExpectedFiles = result[0]["ExpectedFiles"] != System.DBNull.Value ? Convert.ToInt32(result[0]["ExpectedFiles"]) : 0,
                    CurrentFileCount = result[0]["CurrentFileCount"] != System.DBNull.Value ? Convert.ToInt16(result[0]["CurrentFileCount"]) : 0,
                };
                return row;
            }
            return new OsaDataExtractStatus();

        }

        public CompletedAnalysisDate GetCompleteStreamsCount_NHM(string connStr)
        {
            var dataset = ReportingDataGetter.GetCompleteStreamsCount_NHM(connStr);
            var result = dataset.Tables[0].AsEnumerable().ToList();

            if (result != null && result.Count == 1)
            {
                var row = new CompletedAnalysisDate
                {
                    AnalysisDate = result[0]["AnalysisDate"] != System.DBNull.Value ? Convert.ToDateTime(result[0]["AnalysisDate"]).ToString("dd/MM/yyyy") : string.Empty,
                    CompleteCount = result[0]["CompleteCount"] != System.DBNull.Value ? result[0]["CompleteCount"].ToString() : string.Empty,
                    StreamsCount = result[0]["StreamsCount"] != System.DBNull.Value ? result[0]["StreamsCount"].ToString() : string.Empty
                };
                return row;

            }
            return new CompletedAnalysisDate();
        }

    }
}

Walmart-Admin-Dashboard/Controllers/StagingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Walmart_Admin_Dashboard.Helper;
using Walmart_Admin_Dashboard.Models;

namespace Walmart_Admin_Dashboard.Controllers
{
    public class StagingController : Controller
    {
        // GET: Staging
        public ActionResult Index(int? cid)
        {
            if (cid == null)
            {
                cid = TempData["cid"] != null ? Convert.ToInt16(TempData["Cid"]) : 1;
            }
            
            var str = cid == 1 ? "USPROD" : "USCERT";

            var dataset = GetStagingData(str, string.Empty, string.Empty, string.Empty, null,null, "FC");

            var taskHistory = dataset.Tables[3].AsEnumerable().ToList();
            var taskHistoryData = new List<TaskHistoryViewModel>();
            if (taskHistory != null)
            {
                taskHistoryData = GetTaskHistoryData(taskHistory).ToList();
            }

            var tasksInProgressData = new List<TasksInProgressViewModel>();
            var taskInProgress = dataset.Tables[2].AsEnumerable().ToList();
            if(taskInProgress!=null)
            {
                tasksInProgressData = GetTasksInProgressData(taskInProgress).ToList();
            }
            

            var model = new StagingDataModel()
            {
                TaskHistory = taskHistoryData,
                TasksInProgress = tasksInProgressData,
            };
            TempData["cid"] = cid;
            ViewBag.Conn = str;
            return View("Index", model);
    }

        public ActionResult ApplyFilter(string cid, string status, string taskDescr, string fileName, DateTime? taskStart, DateTime? taskEnd, string market)
        { 
            if (cid == null)
            {
                cid = TempData["cid"] != null ? TempData["Cid"].ToString() : "1";
            }

            var str = cid == "1" ? "USPROD" : "USCERT";
            var dataset = GetStagingData(str,status, taskDescr, fileName, taskStart, taskEnd, market);
            var taskHistory = dataset.Tables[3].AsEnumerable().ToList();
            var taskHistoryData = new List<TaskHistoryViewModel>();
            if (taskHistory != null)
            {
                taskHistoryData = GetTaskHistoryData(taskHistory).ToList();
            }
            var tasksInProgressData = new List<TasksInProgressViewModel>();
            var taskInProgress = dataset.Tables[2].AsEnumerable().ToList();
            if (taskInProgress != null)
            {
                tasksInProgressData = GetTasksInProgressData(taskInProgress).ToList();
            }


            var model = new StagingDataModel()
            {
                TaskHistory = taskHistoryData,
                TasksInProgress = tasksInProgressData,
            };
            TempData["cid"] = cid;
            ViewBag.Conn = str;
           // return View("Index", model);

            return PartialView("_StagingView", model);
        }
        private DataSet GetStagingData(string connStr, string status,string taskDescr,  string fileName, DateTime? taskStart, DateTime? taskEnd, string market)
        {
            return ReportingDataGetter.GetStagingQuery(connStr, status, taskDescr, fileName, taskStart, taskEnd, market);
        }
        public IEnumerable<TaskHistoryViewModel> GetTaskHistoryData(List<DataRow> result)
        {
            var list = new List<TaskHistoryViewModel>();
           
                foreach (var item in result)
                {

                    var row = new TaskHistoryViewModel
                    {
                        Market = item["Market"] != DBNull.Value ? item["Market"].ToString() : "FC",
                        TaskDescription = item["TaskDescription"] != System.DBNull.Value ? item["TaskDescription"].ToString() : string.Empty,
                        ProcMins = item["ProcMins"] != System.DBNull.Value ? Convert.ToInt32(item["ProcMins"]) : 0,
                        TaskID = item["TaskID"] != System.DBNull.Value ? item["TaskID"].ToString() : string.Empty,
                        FileName = item["FileName"] != System.DBNull.Value ? item["FileName"].ToString() : string.Empty,
                        ControlID = item["ControlID"] != System.DBNull.Value ? item["ControlID"].ToString() : string.Empty,
                        TaskStart = item["TaskStart"] != System.DBNull.Value ? Convert.ToDateTime(item["TaskStart"]).ToString("dd/MM/yyyy HH:mm") : string.Empty,
                        TaskEnd = item["TaskEnd"] != System.DBNull.Value ? Convert.ToDateTime(item["TaskEnd"]).ToString("dd/MM/yyyy HH:mm") : string.Empty,
                        StatusCode = item["StatusCode"] != System.DBNull.Value ? item["StatusCode"].ToString() : string.Empty,
                        AttemptNo = item["AttemptNo"] != System.DBNull.Value ? item["AttemptNo"].ToString() : string.Empty,
                    };
                    list.Add(row);
                }
            
            return list;
        }
        public IEnumerable<TasksInProgressViewModel> GetTasksInProgressData(List<DataRow> result)
        {
            var list = new List<TasksInProgressViewModel>();
           
                foreach (var item in result)
                {

                    var row = new TasksInProgressViewModel
                    {
                        TaskDescription = item["TaskDescription"] != System.DBNull.Value ? item["TaskDescription"].ToString() : string.Empty,
                        ProcMins = item["ProcMins"] != System.DBNull.Value ? Convert.ToInt32(item["ProcMins"]) : 0,
                        TaskID = item["TaskID"] != System.DBNull.Value ? item["TaskID"].ToString() : string.Empty,
                        TaskInstanceID = item["TaskInstanceID"] != System.DBNull.Value ? item["TaskInstanceID"].ToString() : string.Empty,
                        TaskStart = item["TaskStart"] != System.DBNull.Value ? Convert.ToDateTime(item["TaskStart"]).ToString("dd/MM/yyyy HH:mm") : string.Empty
                       
                    };
                    list.Add(row);
                }
            
            return list;
        }
        
    }
}

Walmart-Admin-Dashboard/Views/Processing/Index.cshtml
@model Walmart_Admin_Dashboard.Models.OscaProcessViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Osca Processing";
    var cid = TempData["cid"];
    var rptDate = Model.ProcessingCompleteStatus.FCCompletedAnalysisDt.AnalysisDate;
}
<h2>Walmart OSCA Data Processing Details</h2>
<div class="row" style="margin:15px 0">
    <div class="col-md-4">
        <span style="font-size: 1.5rem; font-weight:500">Database: @ViewBag.Conn  </span>
    </div>
    <div class="col-md-4">
        <span style="font-size: 1.5rem; font-weight:500">Analysis Date: @rptDate  </span>
    </div>
    <div class="col-md-2">
        @Html.ActionLink("View Staging", "Index", "Staging", new { cid = cid }, new { @class = "btn" })
    </div>
    <div class="col-md-2">
        @Html.ActionLink("View Dashboard", "Index", "Dashboard", new { cid = cid }, new { @class = "btn" })
    </div>
  </div>

@Html.Partial("_CompleteProcessing", Model.ProcessingCompleteStatus)

<h4>Still to process on FC </h4>


@if (Model != null)
{
    if (Model.FCStillToProcess != null && Model.FCStillToProcess.Count() > 0)
    { @Html.Partial("_StillToProcess", Model.FCStillToProcess)}
    else
    { <p>Processing is finished for today</p>}

    <h4>Still to process on NHM </h4>
    if (Model.NHMStillToProcess != null && Model.NHMStillToProcess.Count() > 0)
    {@Html.Partial("_StillToProcess", Model.NHMStillToProcess) }
    else
    { <p>Processing is finished for today</p>}

    <h4>Still to process on GM </h4>
    if (Model.GMStillToProcess != null && Model.GMStillToProcess.Count() > 0)
    {@Html.Partial("_StillToProcess", Model.GMStillToProcess) }
    else
    { <p>Processing is finished for today</p>}

    if (Model.GMCopyover != null && Model.GMCopyover.Count() > 0)
    {
        <h4> GM Copy Over</h4>
        <input type="checkbox" id="ShowHistoryChk" title="Show History">
        <label for="ShowHistoryChk" id="lbl">Show History</label>

                <div id="gmPartial">
                    @Html.Partial("_GMCopyOver", Model.GMCopyover)
                </div>
    }

}

Walmart-Admin-Dashboard/Views/Processing/_GMCopyover.cshtml
@model IEnumerable<Walmart_Admin_Dashboard.Models.GMCopyoverViewModel>
@using (Html.BeginForm("GMCopyover"))
{
<table class="table table-striped table-bordered dashboard-table">
    <thead class="headerRow">
        <tr >
            <th> Analysis Date</th>
            <th> Table Name</th>
            <th> AvgTransferDuration</th>
            <th> Streams Complete</th>
            <th> Mainland Complete</th>
            <th> 159 Complete Time</th>
            <th> 160 Complete Time</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AnalysisDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TableName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvgTransferDuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumComplete) / 60
            </td>
            @{
                var bgColour = "";
                if (!String.IsNullOrEmpty(item.MainlandComplete))
                {
                    var value = Convert.ToDateTime(item.MainlandComplete);
                    bgColour = (value.Hour > 7 || (value.Hour == 7 && value.Minute > 0)) ? "background-color:#ffc7ce"
                        : (value.Hour <= 7) ? "background-color:#c6efce"
                        : "";
                }
                    <td style=@bgColour>@item.MainlandComplete</td>


                if (!String.IsNullOrEmpty(item.Complete159))
                {
                    var value159 = Convert.ToDateTime(item.Complete159);
                    bgColour = (value159.Hour > 7 || (value159.Hour == 7 && value159.Minute > 0)) ? "background-color:#ffc7ce"
                      : (value159.Hour <= 7) ? "background-color:#c6efce"
                      : "";
                }
                    <td style=@bgColour> @item.Complete159 </td >


                if (!String.IsNullOrEmpty(item.Complete160))
                {
                    var value160 = Convert.ToDateTime(item.Complete160);
                    bgColour = (value160.Hour > 7 || (value160.Hour == 7 && value160.Minute > 0)) ? "background-color:#ffc7ce"
                        : (value160.Hour <= 7) ? "background-color:#c6efce"
                        : "";
                }
                <td style=@bgColour>@item.Complete160</td>


                }
        </tr>
                }
    </tbody>
</table>
}


<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        
        $('#ShowHistoryChk').change(function () {
            var cid = getQueryStringValue("cid")
            LoadPartial(cid, this.checked);
        });

        function LoadPartial(cid, chk) {
            $("#gmPartial").load('@Url.Action("LoadGMCopyover", "Processing")', {cid:cid, chk: chk });
        }
    });

   
</script>
<style>
.greenBg {background-color:#c6efce;}
.redBg {background-color:#ffc7ce;}

</style>

Walmart-Admin-Dashboard/Views/Processing/_StillToProcess.cshtml
@model IEnumerable<Walmart_Admin_Dashboard.Models.StillToProcessViewModel>

<table class="table table-striped table-bordered dashboard-table">
    <thead class="headerRow">
        <tr>
            <th>ControlID</th>
            <th>TimeBucket</th>
            <th>StreamID</th>
            <th>Analysis Date</th>
            <th>Run Start</th>
            <th>Stage Start</th>
            <th>Stage End</th>
            <th>Extract Start</th>
            <th>Extract End</th>
            <th>Duration</th>
        </tr>
    </thead>
    <tbody style="font-size: 12px;">
        @if (Model != null)
            {
                foreach (var item in Model)
                {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ControlID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TimeBucket)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StreamID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AnalysisDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ControlRunStartDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ControlStageStartDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ControlStageEndDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ControlExtractStartDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ControlExtractEndDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duration)
                    </td>

                </tr>

            }
        }
    </tbody>
</table>